### PR TITLE
Updated Gif

### PR DESCRIPTION
**Pull request by borgmanJeremy**

### CODE REVIEW

**Comment by borgmanJeremy** [comment]
@mmahmoudian @ZetaoYang Updated gif.

**Comment by ZetaoYang** [comment]
Good work! I'm ok, but I'm not able to approve and merge it.

**Comment by mmahmoudian** [comment]
Regarding the .gif file there are few points that might worth considering:
1. File size
    - the new one is about 1.9MB vs the old one 331.9KB
    - The user should be able to load the page it relatively fast and the page has other elements too.
2. Dimension
    - the new one is 1613x1002, and the old one has 872x426
    - It should fit the page.
    - I think using Peek can help here
3. it should show most, if not all, main features
    - [x] arrow
    - [x] highlight
    - [x] geometric shapes
    - [x] blur/pixelated
    - [x] changing color
    - [x] numbered circles (I forgot its official name)
    - [x] pining
    - [ ] text (you tried, but at the end, the yellow "Hello" disappeared)
    - [ ] changing size/thickness
    - [ ] moving and resizing the selected area (many other screenshot tools don't let you change and move the area)

**Comment by borgmanJeremy** [comment]
@mmahmoudian Thanks for the feedback, I can get most done those things addressed today.

I did make the size different intentionally to capture the upper left of the screen to show the thickness indicator. Do you want to keep the original dimensions?

In either case I will compress the image to reduce the size.

**Comment by borgmanJeremy** [comment]
@mmahmoudian Okay checkout the new gif. If you still want changes feel free to make your own. This is not an area of my expertise :)

By the way do you have the ability to merge in this repo or do we need Lupo?

**Comment by mmahmoudian** [comment]
@borgmanJeremy This is perfect as it also shows the sidebar 👍🏼 Well done!
Yes I can do merge in this repo. I'll merge this one.

**Pull request merged**
