### PR TITLE
Zola Merge

### PR DESCRIPTION
**Pull request by borgmanJeremy**
Needed to re submit the PR after resolving conflicts

### CODE REVIEW

**Comment by borgmanJeremy** [comment]
@mmahmoudian @Correct-Syntax I created this PR after resolving the merge conflicts but the pipeline fails. 

Before we merge this do I need to generate a secure token and store it in the vault?

**Comment by Correct-Syntax** [comment]
@borgmanJeremy I believe I had to setup Actions Secrets in order for it to work.

Mine is setup like:

TOKEN
github-pages 

Repository secrets
GP_TOKEN

**Comment by mmahmoudian** [comment]
> do I need to generate a secure token and store it in the vault?

I don't see why it would nee a secret token! I'll investigate as well

**Comment by mmahmoudian** [comment]
our [current Action file](https://github.com/flameshot-org/flameshot-org.github.io/blob/0bfaa40a5212475f68e889bb32800b02d5d55ea3/.github/workflows/publish.yml) for mkdocs does not use any token and it works just fine. According to the [shalzz/zola-deploy-action](https://github.com/shalzz/zola-deploy-action#secrets) which we will use for Zola:

> `TOKEN`: [Personal Access key](https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line) with the appropriate scope. If the repository is public the public_repo scope suffices

I don't see why we would need to define a token, but considering the error we got in the GH Page check, we would need to define a secret in [the environment](https://github.com/flameshot-org/flameshot-org.github.io/settings/environments/750028/edit).

**Pull request merged**
