### PR TITLE
Add hotkeys, incl. macOS + Windows global hotkeys

### PR DESCRIPTION
**Pull request by karlhorky**
Supersedes https://github.com/flameshot-org/flameshot-org.github.io/pull/31

Updated hotkeys taken from this PR: https://github.com/flameshot-org/flameshot#1097

Ref: https://github.com/flameshot-org/flameshot/issues/1593

cc @ZetaoYang

### CODE REVIEW

**Comment by mmahmoudian** [comment]
@karlhorky The previous reference you provided was not a valid URL. I took the liberty of modifying your post and correcting the URL.

**Comment by mmahmoudian** [comment]
Thank you for the contribution. After reading your changes, I have only one major comment and one very minor comment:

**The major one:** You have used capital letters for keybindings, but the fact is that pressing the capital letters does not work. This is not your fault as the tooltips in Flameshot are all in caps, which is misleading. They should be fixed and I'll file a bug report for those in the Flameshot repo. I would be thankful if you can fix the issue in this PR.

image


**The minor one:** would you please also add a small sentence above the table and say that these keybindings are the default one and user have the option to modify them.

**Comment by karlhorky** [comment]
Done in caed9929776faebbaf68a9bb4fbc8e1fbb8ebbc1

**Comment by mmahmoudian** [comment]
I also reported the bug in

- https://github.com/flameshot-org/flameshot/issues/2856

**Comment by karlhorky** [comment]
Great thanks! And thanks for the merge :)

**Comment by mmahmoudian** [comment]
Thank you for the PR. It is highly appreciate :+1:

**Pull request merged**
