### PR TITLE
Update OSX Installation for Sonoma

### PR DESCRIPTION
**Pull request by Karreg**
Fix https://github.com/flameshot-org/flameshot/issues/3572

Content comes from https://github.com/flameshot-org/flameshot?tab=readme-ov-file#macos

### CODE REVIEW

**Comment by mmahmoudian** [comment]
Thanks for the PR and contributing to the documentation. I just have a small formatting comment:

I believe the following is ambigious due to quoting inside the quote:

> If you see the message “flameshot” cannot be opened because the developer cannot be verified. you will need to follow the steps below:

I suggest putting the message part in a backtick and a quick workaround:

```
If you see the message `“flameshot” cannot be opened because the developer cannot be verified.` you will need to follow the steps below:
```

which will look like:

> If you see the message `“flameshot” cannot be opened because the developer cannot be verified.` you will need to follow the steps below:

**Comment by Karreg** [comment]
Thanks for your quick review. Fair enough I'll do the fix :)

**Comment by Karreg** [comment]
I have applied the change to some more filenames and menu items.

**Review by mmahmoudian — APPROVED** [review]

**Comment by mmahmoudian** [comment]
@Karreg Thanks for the PR and helping the project.

**Comment by mmahmoudian** [comment]
> I have applied the change to some more filenames and menu items.

If you wish to create PR for those too feel free to send the PR any help is welcome.

**Comment by Karreg** [comment]
> > I have applied the change to some more filenames and menu items.
> 
> If you wish to create PR for those too feel free to send the PR any help is welcome.

I have done it in this PR in fact ☺️ 
You're welcome, thank you for this marvelous tool!

**Pull request merged**
