### PR TITLE
Update download section to latest v12.0.0

### PR DESCRIPTION
**Pull request by sida-khalibre**
Should change to some general word example **Latest Version** so avoid this repetitive change?

### CODE REVIEW

**Comment by sida-khalibre** [comment]
> You are right. Do you want to do this change yourself?
I can do that.
What is your suggestion? How about **"Getting Latest Flameshot"**?

**Comment by mmahmoudian** [comment]
> What is your suggestion? How about **"Getting Latest Flameshot"**?

Yeah that would do. Thanks

**Comment by sida-khalibre** [comment]
@mmahmoudian done please check.

**Comment by mmahmoudian** [comment]
@sida-khalibre thanks 👍

**Pull request merged**
